---
# Run some tasks to install dependencies
- name: install dependency packages (RedHat)
  when: ansible_os_family == 'RedHat'
  yum: name={{ item }} state=latest
  with_items:
    - zip
    - unzip
    - wget
    - sysstat
    - ntp
    - telnet
- name: configure ntp (Redhat)
  when: ansible_os_family == 'RedHat'
  service: name=ntpd enabled=yes state=restarted
