---
# configure the utility host
- hosts: utility
  vars:
   var_remote_user: centos
   var_sudo: yes
   var_java_ver: 8u131
   var_java_build: b11
  remote_user: "{{ var_remote_user }}"
  sudo: "{{ var_sudo }}"
  tasks:
  - include: common.yaml
  - name: install EPEL yum repo (RedHat)
    when: ansible_os_family == 'RedHat'
    yum: name=http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
  - name: install ansible (RedHat)
    when: ansible_os_family == 'RedHat'
    yum: name=ansible state=latest
  - name: copy the ansible inventory file
    copy: src=ansiblehosts.txt dest=/etc/ansible/hosts owner=root group=root mode=0644
  - name: fetch the Ambari yum repo (RedHat)
    when: ansible_os_family == 'RedHat'
    command: 'wget -nv http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.5.1.0/ambari.repo -O /etc/yum.repos.d/ambari.repo'
  - name: install the ambari server
    yum: name=ambari-server state=latest
  - name: configure the ambari server
    command: ambari-server setup -j /usr/java/default -s
  - name: Disable CSRF
    lineinfile: 
            dest: /etc/ambari-server/conf/ambari.properties
            insertafter: EOF 
            line: 'api.csrfPrevention.enabled=false'
  - name: start the ambari server
    command: nohup /etc/init.d/ambari-server start
